# Generated by Django 5.0.6 on 2024-12-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0002_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
